name: lassoesm
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pip
  - pip:
      - torch==2.1.0 
      - transformers==4.35.2
      - datasets
